# Generated by Django 3.1.2 on 2020-10-21 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(default='none', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
                ('choice1_text', models.CharField(max_length=200)),
                ('choice2_text', models.CharField(max_length=200)),
                ('choice3_text', models.CharField(max_length=200)),
                ('choice4_text', models.CharField(max_length=200)),
                ('answer_text', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, max_length=25500, null=True)),
                ('published', models.BooleanField(default=False)),
                ('question_type_cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GK.question_type')),
            ],
        ),
    ]
