# Generated by Django 3.1.2 on 2020-12-25 04:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GK', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
