# Generated by Django 3.1.2 on 2020-12-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='subcategory',
            new_name='subcat',
        ),
    ]
